# Generated by Django 5.0.1 on 2024-01-20 15:41

import backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('token', models.CharField(default=backend.generate_token, max_length=30, verbose_name='Token')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6, verbose_name='Placa de patente')),
                ('brand', models.CharField(max_length=300, verbose_name='Marca')),
                ('color', models.CharField(max_length=300, verbose_name='Color')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.person', verbose_name='Persona')),
            ],
        ),
    ]
