# Generated by Django 5.0.1 on 2024-01-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=3000, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora creación')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.officer', verbose_name='Oficial')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.vehicle', verbose_name='Vehículo')),
            ],
        ),
    ]
